#!/bin/sh
set -eu

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${MYSQL_HEALTHCHECK_USER}'@'localhost' IDENTIFIED BY '${MYSQL_HEALTHCHECK_PASSWORD}';
GRANT USAGE ON *.* TO '${MYSQL_HEALTHCHECK_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL
